def setEnvByBranch(String branchName) {
    if (branchName == 'develop') {
        env.ENVIRONMENT = 'dev'
    } else if (branchName=='stage') {
        env.ENVIRONMENT = 'stage'
    } else if (branchName=='production') {
        env.ENVIRONMENT = 'pro'
    }
}
pipeline {
  agent any
  environment{
    CICD_PARAMS_FOLDER = "${env.WORKSPACE}/cicd/parameters"
    SHELL_SCRIPTS_PATH = "${env.WORKSPACE}/cicd/scripts"
    ARTIFACT_PATH = "${env.WORKSPACE}/artifact"
    INFRA_PATH = "${env.WORKSPACE}/infra"
    DAGS_PATH = "${env.WORKSPACE}/dags"
  }

  stages {
    stage("Checkout") {
      steps {
        checkout scm
      }
    }
    stage("Branch Configuration") {
      steps { 
        script { 
          sh "chmod +x -R ${env.SHELL_SCRIPTS_PATH}" 
          if (!env.BRANCH_NAME) { 
            env.TARGET_BRANCH = "develop" // or some default 
            echo "THIS IS MANUAL DEPLOYMENT ON ${env.TARGET_BRANCH}" 
          } else {
            env.TARGET_BRANCH = env.BRANCH_NAME 
            echo "THIS IS PUSH TRIGGER DEPLOYMENT ON ${env.TARGET_BRANCH}" 
          } 
          if (env.TARGET_BRANCH == 'develop') {
            env.ENVIRONMENT = 'dev' 
          } else if (env.TARGET_BRANCH == 'stage') {
            env.ENVIRONMENT = 'stage' 
          } else if (env.TARGET_BRANCH == 'production') {
            env.ENVIRONMENT = 'pro' 
          } 
          echo "SET ENV ON ${env.ENVIRONMENT}" 
        } 
      } 
    }
    stage("Setting Environment Variables") {
      steps {
        script{

          parameter_file_path = "${env.CICD_PARAMS_FOLDER}/parameters.groovy"
          load "${parameter_file_path}"

          parameter_file_path = "${env.CICD_PARAMS_FOLDER}/${env.ENVIRONMENT}/parameters.groovy"
          load "${parameter_file_path}"

          env.PROJECT_ENV_TFVARS = "${env.INFRA_PATH}/tfvars/${env.ENVIRONMENT}/deploy.tfvars"
          env.PROJECT_TFVARS = "${env.INFRA_PATH}/tfvars/deploy.tfvars"
        }
      }
    }
    stage("Terraform Init & Apply") {
      steps {
        script {
          def command = """
            terraform -chdir=${env.INFRA_PATH} init \
              -backend-config="bucket=${env.TFSTATE_S3_BUCKET}" \
              -backend-config="key=${env.APP_NAME}/terraform.tfstate" \
              -backend-config="region=${env.AWS_REGION}" \
              -backend-config="dynamodb_table=${env.DYNAMODB_CICD_TABLE}"

            terraform -chdir=${env.INFRA_PATH} plan \
              -var-file=${env.PROJECT_ENV_TFVARS} \
              -var-file=${env.PROJECT_TFVARS} \

            terraform -chdir=${env.INFRA_PATH} apply \
              -var-file=${env.PROJECT_ENV_TFVARS} \
              -var-file=${env.PROJECT_TFVARS} \
              -auto-approve
          """
          echo "Deploy App Infrastructure"
          sh command
        }
      }
    }
    stage("Create artifacts") {
      steps {
        script {
          echo "Creating Glue job artifacts"
          sh "${env.SHELL_SCRIPTS_PATH}/package_pyfiles.sh"
        }
      }
    }

    stage("Copy Artifacts to S3") {
      steps {
          sh "aws s3 cp ${env.ARTIFACT_PATH} s3://${env.ARTIFACTS_BUCKET}/glue_jobs/${env.APP_NAME}/ --recursive"
      }
    }

    stage("Copy DAGs to S3") {
      steps {
          sh "aws s3 cp ${env.DAGS_PATH} s3://${env.AIRFLOW_BUCKET}/dags/ --recursive"
      }
    }
  }
  post { 
      always { 
        cleanWs() 
      } 
    }
}
